// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzobscdhawhyadpqqfvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56b2JzY2RoYXdoeWFkcHFxZnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzMyODMsImV4cCI6MjA1NDk0OTI4M30.yfAD3d_sq2F9L-gY05bNPGZ-HFkWt0MhZrpOYLvEyh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);